
GET http://localhost/api/colors
###
# @name addnewCateogory
POST http://localhost/api/categories
Content-Type: application/json

{
    "name": "Hoodie"
}
###
POST http://localhost/api/products
Content-Type: application/json

{
    "name": "Hades BlackWolf White Tee",
    "categoryID": 1,
    "colorID": 2,
    "imgURL": ["https://i.ibb.co/RSGLmrn/t6a.png","https://i.ibb.co/sWSfXdv/t6b.png"]
}

### 
POST http://localhost/api/colors 
Content-Type: application/json

{
    "name": "Yellow"    
}

