
GET http://localhost/api/colors
###
# @name addnewCateogory
POST http://localhost/api/categories
Content-Type: application/json

{
    "name": "Hoodie"
}
###
POST http://localhost/api/products
Content-Type: application/json

{
    "name": "DirtyCoins White Hoodie",
    "categoryID": 4,
    "colorID": 2,
    "imgURL": ["https://i.ibb.co/QXQhdhc/h5a.png","https://i.ibb.co/VVfFW9C/h5b.png"]
}

### 
POST http://localhost/api/colors 
Content-Type: application/json

{
    "name": "Yellow"    
}

################################
DELETE http://localhost/api/categories 
Content-Type: application/json

{
    "id": "5"
}
